### ISSUE TITLE
Updated Model Dependency Jars are not uploading to datastore when Java/Scala model got updated

### ISSUE THREAD

**Issue by ligadata-pokuri** [LigaData/Kamanja#897] opened 2016-01-08 18:35 UTC
Steps to repro

1. Add Java/Scala model with dependency jar
2. Modify Dependency jar
3. Update Java/Scala model with the updated dependency jar in configuration file

**Comment by ligadata-ahmad** [comment] 2016-01-12 21:46
The reason of the issue is that each time we start  MetadataAPI we check if the jar doesn't not exist in /lib/application or if there is a difference in size between what we have in  /lib/application  and what we have in DB  then we download the jar from db.

Then when updating the model we check again if we need to upload new jar to db or not , at this moment the result is  no need to upload because it is the same jar.

**Comment by ligadata-ahmad** [comment] 2016-01-12 22:26
Should we download jars from  db only if they don't exist locally and ignore the size ?

**Comment by ligadata-pokuri** [comment] 2016-01-12 22:39
No we should not do that. We always have to download if the jars sizes are different.

Can you check this way?

Can you upload the JAR and check the following two things
1. Just restart & run the engine without updating model. It has to download the new jar and use it. So, you need to see new results.
2. See whether updating model works fine or not after that, because we already uploaded new jar into HBase. Now it need to download the new jar itself?

**Comment by ligadata-pokuri** [comment] 2016-01-12 22:40
I will give some more information why we should always download if jars are mismatching. We upload the jar only from one place and need to download in all other nodes. If we say if it is already there we don't want to download, engine always uses old version in all other nodes other than where it manually replaced.

**Comment by ligadata-ahmad** [comment] 2016-01-12 23:10
Yes I could see new result after uploading the jar manually .(jar need to be copied to /lib/application after starting MetadataAPI).
Updating model worked fine and the new jar was downloaded from db.

**Comment by ligadata-pokuri** [comment] 2016-01-12 23:15
Ahmad,

We should not copy jar to lib/application. Can you let us know the results just after uploading?

**Comment by ligadata-ahmad** [comment] 2016-01-13 00:26
after uploading the jar using  ./kamanja upload jar /data/Ahmed/Issue897/testjar.jar
I started the Engine then I could see new result  and the new jar was downloaded to /lib/system/

**Comment by ligadata-pokuri** [comment] 2016-05-12 19:36
Making this is not an issue. That is by design we download all the jars from storage to local system if there is any mismatch between jars in storage vs local.

**Comment by ligadata-william** [comment] 2016-05-19 23:10
Closing.

**Closed by ligadata-william** 2016-05-19 23:10 UTC
Labels: Bug, P2, Verify
