### ISSUE TITLE
GenerateMessage.sh creates message with no fields

### ISSUE THREAD

**Issue by ligadata-greg** [LigaData/Kamanja#1398] opened 2016-08-12 20:24 UTC
Hello,
SUMMARY:
When running GenerateMessage.sh using a *.csv data set, no errors are reported, but a JSON message is generated with NO fields.

DETAILS:
Before recording a Kamanja example video, I was going through myself to test and validate our doc, and Shilpa's doc on this specific example.    I am following this doc section:
http://kamanja.org/gen-msg-def-1-5/

and Shilpas "Doc_RunningPMMLModelsInKamanja_1.5.2.docx", run on this same data

hmeq_prep3.csv  is attached, the data set used to try and generate the message.

I have double checked my paths, existence of files, parameters of files to match doc settings (trying to minimize more obvious errors).  I spoke to Dan.  I edited the $KAMANJA_HOME/config/log4j2.xml, to change the parameter value <Root level="DEBUG">.   Below is running with and without debug mode.

------------------------------------
`$ nano ConfigFile_GenerateMessage.properties
       
{
"delimiter": ",",
"outputPath": "/Users/gregmakowski/Documents/KamanjaDemo/hmeq_R_demo ", 
"saveMessage": "false",
"nameSpace": "com.ligadata.kamanja",
"partitionKey": "",
"primaryKey": "",
"timePartition": "",
"messageType": "input",
"messageStructure": "fixed",
"createMessageFrom": "header",
"detectDatatypeFrom": 4 
}

------------------------------------
Gregs-MacBook-Pro:bin gregmakowski$ 
Gregs-MacBook-Pro:bin gregmakowski$ bash GenerateMessage.sh  \
>        --inputfile ~/Documents/KamanjaDemo/testing_R_prep3/hmeq_prep3.csv  \
>        --config /usr/local/bin/Kamanja-1.5.2_2.11/config/ConfigFile_GenerateMessage.properties
[RESULT] - The message changed to mapped because there are some ignored fields ("rec_ID","BAD","TIN_IMO_REASON_DebtCon","TIN_IMO_REASON_HomeImp","TIN_IZR_JOB_Mgr","TIN_IZR_JOB_Office","TIN_IZR_JOB_Other","TIN_IZR_JOB_ProfExe","TIN_IZR_JOB_Sales","TIN_IZR_JOB_Self","TIN_IZR_JOB_Missing","R01_LOAN","IMN_R01_MORTDUE","IMN_R01_VALUE","IMN_R01_YOJ","IMN_R01_DEROG","IMN_R01_DELINQ","IMN_R01_CLAGE","IMN_R01_NINQ","IMN_R01_CLNO","LOG6_DEROG","LOG5_DELINQ","LOG_VALUE")
[RESULT] - message created successfully
[RESULT] - you can find the file in this path /Users/gregmakowski/Documents/KamanjaDemo/hmeq_R_demo/message_20160811042736.json
Gregs-MacBook-Pro:bin gregmakowski$ 

------------------------------------
bash GenerateMessage.sh         --inputfile ~/Documents/KamanjaDemo/testing_R_prep3/hmeq_prep3.csv         --config /usr/local/bin/Kamanja-1.5.2_2.11/config/ConfigFile_GenerateMessage.properties
DEBUG [main] - GenerateMessage.main begins
 INFO [main] - The message changed to mapped because there are some ignored fields ("rec_ID","BAD","TIN_IMO_REASON_DebtCon","TIN_IMO_REASON_HomeImp","TIN_IZR_JOB_Mgr","TIN_IZR_JOB_Office","TIN_IZR_JOB_Other","TIN_IZR_JOB_ProfExe","TIN_IZR_JOB_Sales","TIN_IZR_JOB_Self","TIN_IZR_JOB_Missing","R01_LOAN","IMN_R01_MORTDUE","IMN_R01_VALUE","IMN_R01_YOJ","IMN_R01_DEROG","IMN_R01_DELINQ","IMN_R01_CLAGE","IMN_R01_NINQ","IMN_R01_CLNO","LOG6_DEROG","LOG5_DELINQ","LOG_VALUE")
[RESULT] - The message changed to mapped because there are some ignored fields ("rec_ID","BAD","TIN_IMO_REASON_DebtCon","TIN_IMO_REASON_HomeImp","TIN_IZR_JOB_Mgr","TIN_IZR_JOB_Office","TIN_IZR_JOB_Other","TIN_IZR_JOB_ProfExe","TIN_IZR_JOB_Sales","TIN_IZR_JOB_Self","TIN_IZR_JOB_Missing","R01_LOAN","IMN_R01_MORTDUE","IMN_R01_VALUE","IMN_R01_YOJ","IMN_R01_DEROG","IMN_R01_DELINQ","IMN_R01_CLAGE","IMN_R01_NINQ","IMN_R01_CLNO","LOG6_DEROG","LOG5_DELINQ","LOG_VALUE")
 INFO [main] - message created successfully
 INFO [main] - you can find the file in this path /Users/gregmakowski/Documents/KamanjaDemo/hmeq_R_demo/message_20160812010700.json
[RESULT] - message created successfully
[RESULT] - you can find the file in this path /Users/gregmakowski/Documents/KamanjaDemo/hmeq_R_demo/message_20160812010700.json
Gregs-MacBook-Pro:bin gregmakowski$ 
`

**Comment by ligadata-greg** [comment] 2016-08-12 20:25
the generated file

`Gregs-MacBook-Pro:hmeq_R_demo gregmakowski$ ls -l
total 8
-rw-r--r--  1 gregmakowski  staff  195 Aug 11 16:27 message_20160811042736.json
Gregs-MacBook-Pro:hmeq_R_demo gregmakowski$ 
Gregs-MacBook-Pro:hmeq_R_demo gregmakowski$ 
Gregs-MacBook-Pro:hmeq_R_demo gregmakowski$ head *json
{
  "Message":{
    "NameSpace":"com.ligadata.kamanja",
    "Name":"testmessage",
    "Version":"00.01.00",
    "Description":"",
    "Fixed":"false",
    "Persist":"false",
    "Fields":[]
  }
`

**Comment by ligadata-greg** [comment] 2016-08-12 20:27
[hmeq_prep3.txt](https://github.com/LigaData/Kamanja/files/416118/hmeq_prep3.txt)

**Comment by ligadata-greg** [comment] 2016-08-12 20:28
[RUNNING PMML MODELS IN KAMANJA.pdf](https://github.com/LigaData/Kamanja/files/416119/RUNNING.PMML.MODELS.IN.KAMANJA.pdf)

**Comment by ligadata-greg** [comment] 2016-08-12 20:30
This is a PMML generated by R, which reads the above *.txt file  (I normally save it as a *.csv, but github would not allow attaching of *.csv).

The PMML skips reading the first field, the key field, rec_ID.   The scored records output must exactly match the scored input records.

The attached file is a PMML file.  In order to attach it, I added the *.txt extension.


[hmeq_R_tree_m1.xml.txt](https://github.com/LigaData/Kamanja/files/416123/hmeq_R_tree_m1.xml.txt)

**Comment by ligadata-yousef** [comment] 2016-08-28 12:37
Hi Greg,

to generate a message from a file you should remove double quote from the name of field in file for example: 

"rec_ID","BAD","TIN_IMO_REASON_DebtCon"    should be    rec_ID,BAD,TIN_IMO_REASON_DebtCon

you can pass _ and $ as special character in the name of field because Kamanja use field as variable in scala code so if there are any special characters except _ and $ kamanja will raise an error when trying to add a message in Kamanja.


note:

1- because of this we raised an info like below to tell user that your field name is incorrect.

INFO [main] - The message changed to mapped because there are some ignored fields ("rec_ID","BAD","TIN_IMO_REASON_DebtCon","TIN_IMO_REASON_HomeImp","TIN_IZR_JOB_Mgr","TIN_IZR_JOB_Office","TIN_IZR_JOB_Other","TIN_IZR_JOB_ProfExe","TIN_IZR_JOB_Sales","TIN_IZR_JOB_Self","TIN_IZR_JOB_Missing","R01_LOAN","IMN_R01_MORTDUE","IMN_R01_VALUE","IMN_R01_YOJ","IMN_R01_DEROG","IMN_R01_DELINQ","IMN_R01_CLAGE","IMN_R01_NINQ","IMN_R01_CLNO","LOG6_DEROG","LOG5_DELINQ","LOG_VALUE")

2- change the log to warn instead of info because i see duplicate in message lie below :

INFO [main] - message created successfully
INFO [main] - you can find the file in this path /Users/gregmakowski/Documents/KamanjaDemo/hmeq_R_demo/message_20160812010700.json
[RESULT] - message created successfully
[RESULT] - you can find the file in this path /Users/gregmakowski/Documents/KamanjaDemo/hmeq_R_demo/message_20160812010700.json
Gregs-MacBook-Pro:bin gregmakowski$ 

-- so when you change it to warn you should see:

[RESULT] - message created successfully
[RESULT] - you can find the file in this path /Users/gregmakowski/Documents/KamanjaDemo/hmeq_R_demo/message_20160812010700.json
Gregs-MacBook-Pro:bin gregmakowski$

**Comment by ligadata-ramana** [comment] 2016-09-07 05:46
Yousef is correct. After removing quotes around the fields in hmeq_prep3.txt, GenerateMessage.sh generated the following
{
  "Message":{
    "NameSpace":"com.ligadata.kamanja",
    "Name":"testmessage",
    "Version":"00.01.00",
    "Description":"",
    "Fixed":"true",
    "Persist":"false",
    "Fields":[{
      "Name":"rec_ID",
      "Type":"System.Int"
    },{
      "Name":"BAD",
      "Type":"System.Int"
    },{
      "Name":"TIN_IMO_REASON_DebtCon",
      "Type":"System.Int"
    },{
      "Name":"TIN_IMO_REASON_HomeImp",
      "Type":"System.Int"
    },{
      "Name":"TIN_IZR_JOB_Mgr",
      "Type":"System.Int"
    },{
      "Name":"TIN_IZR_JOB_Office",
      "Type":"System.Int"
    },{
      "Name":"TIN_IZR_JOB_Other",
      "Type":"System.Int"
    },{
      "Name":"TIN_IZR_JOB_ProfExe",
      "Type":"System.Int"
    },{
      "Name":"TIN_IZR_JOB_Sales",
      "Type":"System.Int"
    },{
      "Name":"TIN_IZR_JOB_Self",
      "Type":"System.Int"
    },{
      "Name":"TIN_IZR_JOB_Missing",
      "Type":"System.Int"
    },{
      "Name":"R01_LOAN",
      "Type":"System.Float"
    },{
      "Name":"IMN_R01_MORTDUE",
      "Type":"System.Float"
    },{
      "Name":"IMN_R01_VALUE",
      "Type":"System.Float"
    },{
      "Name":"IMN_R01_YOJ",
      "Type":"System.Float"
    },{
      "Name":"IMN_R01_DEROG",
      "Type":"System.Float"
    },{
      "Name":"IMN_R01_DELINQ",
      "Type":"System.Float"
    },{
      "Name":"IMN_R01_CLAGE",
      "Type":"System.Float"
    },{
      "Name":"IMN_R01_NINQ",
      "Type":"System.Float"
    },{
      "Name":"IMN_R01_CLNO",
      "Type":"System.Float"
    },{
      "Name":"LOG6_DEROG",
      "Type":"System.Float"
    },{
      "Name":"LOG5_DELINQ",
      "Type":"System.Float"
    },{
      "Name":"LOG_VALUE",
      "Type":"System.Float"
    }]
  }
}

I wonder it requires any documentation.

**Comment by ligadata-william** [comment] 2016-09-07 20:19
I've confirmed this is the case. I believe it's standard to not include quotes in CSV headers as it is understood they are all text. However, it wouldn't hurt to document this. I'll close this issue as verified and open a doc bug related to this.

**Closed by ligadata-william** 2016-09-07 20:19 UTC
Labels: Bug, P2, Verify

**Comment by ligadata-william** [comment] 2016-09-07 20:21
#1431 has been opened for documentation purposes.
