### ISSUE TITLE
an update to a container causes JTM to be recompiled

### ISSUE THREAD

**Issue by ligadata-dan** [LigaData/Kamanja#1120] opened 2016-05-04 23:26 UTC
Result: {
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddContainerDef",
    "Result Data" : null,
    "Result Description" : "Container Added Successfully:com.ligadata.kamanja.samples.containers.coughcodes.000000000001000003"
  }
}
RecompileModel results for com.ligadata.kamanja.samples.models.copdriskassessment.1
{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "RemoveModel",
    "Result Data" : null,
    "Result Description" : "Deleted Model Successfully:com.ligadata.kamanja.samples.models.copdriskassessment.000000000000000001"
  }
}{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Model Added Successfully:com.ligadata.kamanja.samples.models.copdriskassessment.000000000000000001"
  }
}
RecompileModel results for com.ligadata.kamanja.samples.models.copddataingest.1
{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "RemoveModel",
    "Result Data" : null,
    "Result Description" : "Deleted Model Successfully:com.ligadata.kamanja.samples.models.copddataingest.000000000000000001"
  }
}{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Model Added Successfully:com.ligadata.kamanja.samples.models.COPDDataIngest.000000000000000001"
  }
}

**Comment by ligadata-dan** [comment] 2016-05-04 23:26
@ligadata-pokuri 

Hi, assigned to you for now.  Not sure if you want Ramana to take a look

**Comment by ligadata-ashish** [comment] 2016-08-12 19:12
@ligadata-dan could you pls provide a 2-3 line description of what the issue is, the impact if not fixed and how should it get fixed.

**Comment by ligadata-dan** [comment] 2016-08-12 20:16
@ligadata-ashish 

I think the issue here is that JTM model does not care about the container, but it is being recompiled.   The thought was that only models that depend on the recompiled container need to be recompiled.

We deemed it to be a low priority at the time.

**Comment by ligadata-william** [comment] 2016-09-09 18:14
I'm seeing two issues here now. One, when I update a container (in the medical app for example), the JTM is no longer being recompiled (which is good) but the copdriskassessment model, which is dependent on it, isn't being recompiled (which is bad).

Another issue is that updating a message (such as hl7) is causing the COPDDataIngest JTM to be recompiled (BAD) instead of its actual dependent model copdriskassessment.

**Comment by ligadata-william** [comment] 2016-09-09 20:26
Issues #1433 & #1434 have been opened to track the issues found in my previous comment.

**Comment by ligadata-ramana** [comment] 2016-09-14 17:24
Both 1433 and 1434 are verified and closed. I can close this ticket.

**Closed by ligadata-ramana** 2016-09-14 17:24 UTC
Labels: Bug, P2
