### ISSUE TITLE
The target data field in PMML should be one of the fields in input message definition.

### ISSUE THREAD

**Issue by ligadata-tulasi** [LigaData/Kamanja#1290] opened 2016-07-04 15:39 UTC

**Comment by ligadata-yousef** [comment] 2016-07-05 20:06
Hi tulasi,

i am working on it and i sent an email to Rich and Greg for some help. 
the problem is when you describe the target field like below it will parse:

  <Targets>
      <Target field="Species" optype="categorical">
        <TargetValue value="setosa"/>
        <TargetValue value="versicolor"/>
        <TargetValue value="virginica"/>
      </Target>
    </Targets>

but if it described like below it will not parse:

<MiningField name="Species" invalidValueTreatment="asIs" usageType="target"/>

**Comment by ligadata-yousef** [comment] 2016-07-10 10:24
fixed.

i added a pull request with this id #1314. @ligadata-tulasi please verify after @ligadata-pokuri or @ligadata-william merged to 1.5.0.Test or you can test it in "GenerateMessageFile-Kamanja-640" branch.

**Comment by ligadata-tulasi** [comment] 2016-07-12 23:31
Verified, the issue is fixed in branch GenerateMessageFile-Kamanja-640.

**Comment by ligadata-shilpa** [comment] 2016-07-21 21:38
This fix isn't included in 1.5.0/1.5.1 .

**Comment by ligadata-greg** [comment] 2016-07-21 21:41
Hello,
Pokuri confirmed this bugfix is not in the latest.  Please include it in the next release.

We will wait on this bugfix to record videos using Kamanja to run models from R or SAS (assuming there will be some small release with it in the next two weeks.)

**Comment by ligadata-william** [comment] 2016-07-25 15:46
If this fix isn't available, I'm removing the verify label.

**Comment by ligadata-pokuri** [comment] 2016-08-01 18:58
this branch is merged to 1.5.2

**Comment by ligadata-pokuri** [comment] 2016-08-01 20:04
This was verified by tulasi

**Closed by ligadata-pokuri** 2016-08-01 20:04 UTC
Labels: Bug, P2, Verify
