### ISSUE TITLE
MetadataAPIService (http://xx.xx.50.72:8081/) is not available after installing v1.0.5 release

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#583] opened 2015-07-29 21:02 UTC
Pre-request 

Start zk, kafka, cassandra and engine
Run metadataAPIService
Started successfully 

Open browser 
Enter http://xx.xx.50.72:8081/

Expected:
API Results displayed

Actual 
This webpage is not available
Connection refused

**Comment by ligadata-william** [comment] 2016-04-26 19:55
@ligadata-dan last I saw this was still an issue.

**Comment by ligadata-pokuri** [comment] 2016-05-20 19:38
This is duplicate of https://github.com/LigaData/Kamanja/issues/723

**Comment by ligadata-yasser** [comment] 2016-05-31 10:07
@ligadata-william 
please verify, pull request is #1195

**Comment by ligadata-william** [comment] 2016-11-08 17:33
Verified as fixed. Closing.

**Closed by ligadata-william** 2016-11-08 17:33 UTC
Labels: Bug, P2, Verify
