### ISSUE TITLE
Feature:  Support JAR models trained by H2O

### ISSUE THREAD

**Issue by ligadata-greg** [LigaData/Kamanja#721] opened 2015-09-08 20:36 UTC
In the big data space, the H2O product is gaining traction for training and executing models on big data.
http://h2o.ai/     It is starting to show up in job requirements for Google and other places.  It is used at Netflix.   http://jobs.monster.com/search/?tjt=data+mining+h2o

They currently do not generate PMML.  They do generate POJO files.  We may want to ask them their intention of generating PMML (one link said it is on the roadmap).
https://groups.google.com/forum/#!topic/h2ostream/nsPguiIgLkk
https://github.com/h2oai/h2o-training/tree/master/tutorials/streaming/storm

WHY WOULD H20 BE INTERESTED?
Because, working with Kamanja, they could import and run PMML models generated by other, more commonly used data mining tools.

SUGGESTION:
1) Contact them (they are in Mountain View by Costco), to ask their ideas for supporting PMML on their roadmap.  http://www.meetup.com/H2Omeetup/

2) Depending on their answer, and feedback from the field, we may want to see what can be done to convert a general POJO file to what is needed for a Kamanja custom Java model.  Can we do more than document this process?  Is there a way we could take a POJO generated to a consistent spec and convert it?  Could we work with H2O to have an option for them to generate their POJO in a Kamanja compatible way?

**Comment by ligadata-damian** [comment] 2016-11-23 19:37
This H2O product seems to be in direct competition with Kamanja, not sure if this means we should close this ticket?:
http://www.h2o.ai/steam/

**Comment by ligadata-william** [comment] 2016-11-23 19:49
H2O jars don't use our interfaces which would make it difficult to execute their jars. Technically, it could be done but I don't see it as a worthwhile effort for the platform team. Since training models in tools that generate PMML seems to still be more widely accepted, I'm not sure what benefit we would get out of this. Ultimately, a question for @ligadata-krishna or @ligadata-ashish on whether or not we would want to actually add such a feature.

**Comment by ligadata-damian** [comment] 2016-11-23 19:51
William, Thanks but I was suggesting we close this ticket rather than investigate further

**Comment by ligadata-william** [comment] 2016-11-23 19:53
I understand that and I, personally, would choose to close it. I'm simply deferring to Krishna or Ashish if there's a legitimate reason (such as a customer request) or intent to add this feature or not before such a choice is made.

**Comment by ligadata-ashish** [comment] 2016-11-23 22:50
They seem to be very much in our space.
http://www.h2o.ai/sparkling-water/

Open to ideas but I did not see an angle/use-case where H2O and Kamanja can be part of the same solution for one of our customers prospects in banking/telecom. Krishna? Will continue to research them but for now, lets close it. I will add it to my Backlog sheet so we track this ask. 

How are POJOs different than the JAVA programs(pseudo-models) that run within Kamanja today?

**Closed** 2016-11-23 23:07 UTC
Labels: Feature Request, P3

**Comment by ligadata-damian** [comment] 2016-11-23 23:09
@ligadata-ashish separately confirmed this issue should be closed
