### ISSUE TITLE
Unable to Update PMML

### ISSUE THREAD

**Issue by ligadata-dan** [LigaData/Kamanja#1113] opened 2016-05-04 04:09 UTC
@ligadata-rich 

pmml model update fails

Result: {
"APIResults" : {
"Status Code" : -1,
"Function Name" : "UpdateModel(type = PMML)",
"Result Data" : null,
"Result Description" : "The model name and new version was not supplied for this PMML model : name= version=null\nOptionally one should consider supplying the exact version of the model being updated, especially important when you are maintaining multiple versions with the same model name and tweaking versions of same for your 'a/b/c...' score comparisons."
}
}

**Comment by ligadata-rich** [comment] 2016-05-04 06:19
see #1110 comment.  We can probably just mark this duplicate of the #1110 ...

**Comment by ligadata-rich** [comment] 2016-05-04 18:21
fix in branch #1085 (Pokuri to merge to test shortly) for the PMML update.  See #1110

**Comment by ligadata-pokuri** [comment] 2016-05-04 18:22
@ligadatahari , can you verify this. Meged issue1085 into 1.4.0.Test

**Comment by ligadatahari** [comment] 2016-05-04 18:46
appears fixed. The problem was the error was thrown when the model did not exist. Opening another bug to throw error properly when the model did not exist

**Closed by ligadatahari** 2016-05-04 18:46 UTC
Labels: Bug, P1, Verify
