### ISSUE TITLE
remove adaptermessagebinding does not work

### ISSUE THREAD

**Issue by ligadatahari** [LigaData/Kamanja#1056] opened 2016-04-27 20:45 UTC
I gave the following command

kamanja remove adaptermessagebinding KEY 'helloworldinput,com.ligadata.kamanja.samples.messages.msg1,com.ligadata.kamanja.serializer.csvserdeser'

I got the following error 

SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
 WARN [main] - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
ERROR [main] - Node Undefined not found in metadata
ERROR [main] - Route not found
Result: {
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "StartMetadataAPI",
    "Result Data" : null,
    "Result Description" : "No value found for 'removeadaptermessagebindinghelloworldinput,com.ligadata.kamanja.samples.messages.msg1,com.ligadata.kamanja.serializer.csvserdeser'"
  }
}

I have attached the kamanja list output

---------------------------------------- Kamanja List Output -----------------------------------------------

Haris-MacBook-Pro:bin hariramasamy$ kamanja list adaptermessagebindings
Unable to find a $JAVA_HOME at "/usr", continuing with system-provided Java...
Using default configuration /Users/hariramasamy/mykamanja/Kamanja-1.4.0_2.11/config/MetadataAPIConfig.properties
 WARN [main] - DATABASE_SCHEMA remains unset
 WARN [main] - DATABASE_LOCATION remains unset
 WARN [main] - DATABASE_HOST remains unset
 WARN [main] - ADAPTER_SPECIFIC_CONFIG remains unset
 WARN [main] - SSL_PASSWD remains unset
 WARN [main] - AUDIT_PARMS remains unset
 WARN [main] - DATABASE remains unset
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/hariramasamy/mykamanja/Kamanja-1.4.0_2.11/lib/system/ExtDependencyLibs2_2.11-1.4.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/hariramasamy/mykamanja/Kamanja-1.4.0_2.11/lib/system/ExtDependencyLibs_2.11-1.4.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
 WARN [main] - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
ERROR [main] - Node Undefined not found in metadata
Result: [
 {
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "ListAllAdapterMessageBindings",
    "Result Data" : "teststatus_1,com.ligadata.kamanjabase.kamanjastatusevent,com.ligadata.kamanja.serializer.csvserdeser",
    "Result Description" : ""
  }
},
{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "ListAllAdapterMessageBindings",
    "Result Data" : "testout_1,com.ligadata.kamanja.samples.messages.outmsg1,com.ligadata.kamanja.serializer.csvserdeser",
    "Result Description" : ""
  }
},
{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "ListAllAdapterMessageBindings",
    "Result Data" : "helloworldinput,com.ligadata.kamanja.samples.messages.msg1,com.ligadata.kamanja.serializer.csvserdeser",
    "Result Description" : ""
  }
} 
]

**Comment by ligadata-rich** [comment] 2016-04-27 21:40
duplicate of #1048.  There is a fix in branch issue1037 for this that **has not been merged**.   

Pokuri will merge... going to close this one.  Follow #1048 for status.

**Closed by ligadata-rich** 2016-04-27 21:40 UTC
Labels: Bug
