### ISSUE TITLE
Delete function when run the second time shows the same list of records

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1010] opened 2016-04-01 18:26 UTC
Delete function when run the second time shows the same list of records when it should go on reducing by one.

**Comment by ligadata-william** [comment] 2016-04-25 21:13
Closing due to age. Will reopen later if it turns out to still be an issue.

**Comment by ligadata-william** [comment] 2016-04-25 21:14
Re-opening this, accidentally closed this thinking it was another issue.

**Comment by ligadata-william** [comment] 2016-04-25 21:15
@ligadata-dhaval please apply the bug label and a priority label to it and assign it to the appropriate person, even if it's yours.

**Comment by ligadata-ashish** [comment] 2016-08-12 19:25
@ligadata-alison We don't support "user defined functions" in the product at this point in time. @ligadata-dhaval please check the code to ensure that this functionality is disabled.

**Comment by ligadata-alison** [comment] 2016-08-12 19:29
What about macros and constants?

http://kamanja.org/advanced-developers-guide-1-5/models-1-5/kpmml-1-5/udfs-macros-constants-1-5/

**Comment by ligadata-alison** [comment] 2016-08-12 19:53
sorry - I meant - what about user-defined properties?

**Comment by ligadata-dhaval** [comment] 2016-08-19 18:20
Commented the higher level call to functions. Please find the below result:

Unexpected action! action=addfunction
Result: {
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "StartMetadataAPI/route",
    "Result Data" : null,
    "Result Description" : "Unexpected action! action = addfunction"
  }
}

Also removed from help command. 

Branch: github_1010

**Comment by ligadata-dhaval** [comment] 2016-08-19 18:25
Pull request: 1405

https://github.com/LigaData/Kamanja/pull/1405

**Comment by ligadata-dhaval** [comment] 2016-08-19 18:26
@ligadata-alison Could you please update the documentation accordingly.

**Comment by ligadata-alison** [comment] 2016-08-19 18:30
Hi Dhaval,
     Would you please take a look at the following page:

http://kamanja.org/advanced-developers-guide-1-5/models-1-5/kpmml-1-5/udfs-macros-constants-1-5/

and let me know what else is not currently supported?

thanks,
alison

**Comment by ligadata-dhaval** [comment] 2016-08-19 19:06
I don't think there should be any changes. I can see for UDF doc says deprecated. That should be fine.

**Comment by ligadata-alison** [comment] 2016-08-19 20:04
great - thank you Dhaval - I think we can close this issue - the
documentation is up-to-date

**Comment by ligadata-william** [comment] 2016-09-09 18:45
Functions operations are confirmed removed in branch 1.6.0. Closing as this issue is no longer valid.

**Closed by ligadata-william** 2016-09-09 18:45 UTC
Labels: Bug, P2, Verify
