### ISSUE TITLE
Issue with Scala version validation during cluster installation

### ISSUE THREAD

**Issue by ligadata-dan** [LigaData/Kamanja#1260] opened 2016-06-29 06:02 UTC
@ligadata-pokuri @ligadata-ramana 

Hi guys, so I have tried this several times,  Both 1.3->1.5 and 1.4 -> 1.5 (both build with scala 2.11).  If this is user error, please let me know.  For now I am ignoring scala validation during my testing

**Scala Installed**
Dans-MacBook-Pro-2:ClusterInstall dankozin$ which scala
/Users/dankozin/scala-2.11.5/bin/scala

**Command**:

bash ClusterInstallerDriver-1.5.0 --upgrade --apiConfig /Users/dankozin/MetadataAPIConfig.properties --clusterConfig /Users/dankozin/ClusterConfig.json --tarballPath /Users/dankozin/Kamanja-1.5.0_2.11.tar.gz --toScala "2.11" --fromKamanja "1.3" --fromScala "2.11" --tenantId tenant1 --adapterMessageBindings /tmp/newBindings

**Output**

DEBUG [main] - Found PhysicalRootDir:/Users/dankozin/Kamanja-1.5.0_2.11
DEBUG [main] - Components Results:[{"version":null,"status":"Success","errorMessage":null,"componentName":"zookeeper"},{"version":null,"status":"Success","errorMessage":null,"componentName":"kafka"},{"version":null,"status":"Success","errorMessage":null,"componentName":"hbase"},{"version":null,"status":"Fail","errorMessage":null,"componentName":"scala"},{"version":"1.7.0_79","status":"Success","errorMessage":null,"componentName":"java"}]
ERROR [main] - Scala for ip localhost is not same as 2.11 or invalid... msg=
Scala for ip localhost is not same as 2.11 or invalid... msg=
ERROR [main] - The cluster environment is not suitable for an installation or upgrade... look at the prior log entries for more information.  Corrections are needed.
The cluster environment is not suitable for an installation or upgrade... look at the prior log entries for more information.  Corrections are needed.
DEBUG [main] -
Usage:

**Comment by ligadata-dan** [comment] 2016-06-29 06:03
@ligadata-pokuri 
Assigning to you since I am not sure if ramada is around or if this is simply a user error.

**Comment by ligadata-ramana** [comment] 2016-09-14 15:39
Unable to reproduce the issue. Also checked with Dan to make sure I am not missing in scenario. Closing the ticket as a non-issue for now

**Closed by ligadata-ramana** 2016-09-14 15:39 UTC
Labels: Bug, Cx, P2
